### ISSUE TITLE
Module stopped working

### ISSUE THREAD

**Issue by clintallan** [soulseekah/prestashop-variable-shipping#1]
This module has all of a sudden stopped working. It was working perfectly until today. when you enter the price it doesn't update. Any ideas?

**Comment by soulseekah** [comment]
What version of PrestaShop are/were you running? What changed from the last time it worked?

**Comment by clintallan** [comment]
1.5.6.2
Nothing has changed. I have made no changes to the site other than add stock. it worked yesterday and now today it doesn't. I have removed the module and reinstalled but still the same. It all appears but when you enter the price and click update shipping remains 0. This is an excellent module that saves a lot of time for us so I am keen to get this working

Thanks for the speedy reply also

**Comment by soulseekah** [comment]
Check the error log, the AJAX request is probably failing due to something that did change without you even knowing, like your host updated PHP or something.

**Comment by soulseekah** [comment]
You can find my e-mail in my profile, send over some access details, I can check things out myself if you like.

**Comment by clintallan** [comment]
Just been looking in the logs (cpanel) nothing of interest in there. I shall email you access details over shortly. Thank you for your help

**Comment by soulseekah** [comment]
OK. It could be that your /tmp directory is no longer writable (or full), just a guess. Will know more after looking at the exact AJAX response and the logs. Talk soon.

**Comment by soulseekah** [comment]
Server misconfiguration (invalid redirects).
