### ISSUE TITLE
Include tax calculation with shipping

### ISSUE THREAD

**Issue by clintallan** [soulseekah/prestashop-variable-shipping#2]
The module does not include tax. If it could include carrier tax it would be much better

**Comment by tucoinfo** [comment]
@clintovsina it works just fine for me. Maybe you should double check your PS config (Tax rules, Transporters, etc)

**Comment by soulseekah** [comment]
@tucoinfo, do you get Tax calculated in the shipping slip with the right configs?

**Comment by tucoinfo** [comment]
@soulseekah The delivery slip PDF does not show VAT. Only paymethod and total in my version (on the left). I don't use this PDF but I would delete this info for shipping security reasons. The invoice PDF shows correct VAT (for product and shipping costs) on the right. The VAT recap at the bottom attributes all VAT to a single entry called Products. Does that answer your question?

**Comment by clintallan** [comment]
On the invoice the "total vat" is only the vat from the products, not from the shipping. As you alter shipping costs whilst using this feature the figure "total vat" does not change.

I do not use the shipping slip. It is the invoice I use

**Comment by clintallan** [comment]
@tucoinfo Are you sure tax is being applied to the carrier? I've checked my set up and it all seems right. Tax is being applied to products but NOT to shipping when I use this module. The total tax is just the tax of the products and no matter what I set shipping at the tax figure remains the same.

**Comment by tucoinfo** [comment]
@clintovsina Yes I think so. Here are screenshots with variable shipping and other shipping.

![1](https://cloud.githubusercontent.com/assets/1420304/2818401/24df68f0-cee4-11e3-976d-22cc030f20ac.png)
![2](https://cloud.githubusercontent.com/assets/1420304/2818406/36a1bcb4-cee4-11e3-97e3-8284343ee45b.png)
